# SPDX-License-Identifier: MPL-2.0
name = "HardwareResilience"
uuid = "01a11d29-d880-869f-9c60-029824b42355"
authors = ["Jonathan D.A. Jewell <j.d.a.jewell@open.ac.uk>"]
version = "0.1.1"
license = "MPL-2.0"

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"

[compat]
Dates = "1"
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
